/*
 * OpenApi Course
 * Specification for OpenApi Course
 *
 * OpenAPI spec version: 1.0
 * Contact: example@example.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Beer;
import io.swagger.client.model.BeerPagedList;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for BeersApi
 */
@Ignore
public class BeersApiTest {

    private final BeersApi api = new BeersApi();

    /**
     * New Beer
     *
     * Create a new **Beer** Object
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createBeerTest() throws Exception {
        Beer body = null;
        api.createBeer(body);

        // TODO: test validations
    }
    /**
     * Delete Beer by Id
     *
     * Delete **Beer** by Id
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteBeerByIdTest() throws Exception {
        UUID beerId = null;
        api.deleteBeerById(beerId);

        // TODO: test validations
    }
    /**
     * Beer by Id
     *
     * Get details of **Beer** by id
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getBeerByIdTest() throws Exception {
        UUID beerId = null;
        Beer response = api.getBeerById(beerId);

        // TODO: test validations
    }
    /**
     * List of Beers
     *
     * Get a list of **Beers** in the system.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getListOfBeersTest() throws Exception {
        Integer pageNumber = null;
        Integer pageSize = null;
        BeerPagedList response = api.getListOfBeers(pageNumber, pageSize);

        // TODO: test validations
    }
    /**
     * Modify of Beer
     *
     * Modify **Beer** by Id
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void modifyBeerByIdTest() throws Exception {
        Beer body = null;
        UUID beerId = null;
        api.modifyBeerById(body, beerId);

        // TODO: test validations
    }
}
