openapi: 3.0.2
info:
  version: '1.0'
  title: OpenApi Course
  description: Specification for OpenApi Course
  termsOfService: http://example.com/terms/
  contact:
    name: FReni
    email: example@example.hu
    url: https://www.example.com/support/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://dev.example.com
    description: Development Server
  - url: https://qa.example.com
    description: QA Server
  - url: https://prod.example.com
    description: Production Server
paths:
  /app/customers:
    get:
      responses:
        '202':
          description: List of Customers
    put:
      responses:
        '202':
          description: Modify of Customers
  /app/beers:
    get:
      responses:
        '202':
          description: List of Beers
        '404':
          description: No Beers Found
