openapi: 3.0.2
info:
  version: '1.0'
  title: OpenApi Course
  description: Specification for OpenApi Course
  termsOfService: http://example.com/terms/
  contact:
    name: FReni
    email: example@example.hu
    url: https://www.example.com/support/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://dev.example.com
    description: Development Server
  - url: https://qa.example.com
    description: QA Server
  - url: https://prod.example.com
    description: Production Server
paths:
  /app/customers:
    get:
      responses:
        '200':
          description: List of Customers
          content:
            application/json:
              schema:
                type: array
                minItems: 1
                maxItems: 100
                description: List of Customers
                items:
                  type: object
                  description: Customer Object
                  properties:
                    id:
                      type: string
                      format: uuid
                    firstName:
                      type: string
                      minLength: 2
                      maxLength: 100
                      example: Renata
                    lastName:
                      type: string
                      minLength: 2
                      maxLength: 100
                      example: Figler
                    address:
                      type: object
                      properties:
                        line:
                          type: string
                          example: Kinizsi ut 2/B
                        city:
                          type: string
                          example: Budaörs
                        stateCode:
                          type: string
                          minLength: 2
                          maxLength: 2
                          description: 2 Letter State Code
                          # enum: [AL, AK, AZ, AR, CA]
                          enum:
                            - AL
                            - AK
                            - AZ
                            - AR
                            - CA
                        zipCode:
                          type: integer
                          example: 2040
    put:
      responses:
        '200':
          description: Modify of Customers
  /app/beers:
    get:
      responses:
        '200':
          description: List of Beers
          content:
            application/json:
              schema:
                type: array
                minItems: 1
                maxItems: 100
                description: List of Beers
                items:
                  type: object
                  description: Beer Object
                  properties:
                    id:
                      type: string
                      format: uuid
                    name:
                      type: string
                    style:
                      type: string
                      enum:
                        - ALE
                        - PALE_ALE
                        - IPA
                        - WHEAT
                        - LAGER
                    upc:
                      type: string
                    price:
                      type: number
                      format: float
                    quantity:
                      type: integer
                      format: int32
                    brewery:
                      type: object
                      properties:
                        name:
                          type: string
                        location:
                          type: string
        '404':
          description: No Beers Found