openapi: 3.0.2
info:
  version: '1.0'
  title: OpenApi Course
  description: Specification for OpenApi Course
  termsOfService: http://example.com/terms/
  contact:
    name: FReni
    email: example@example.hu
    url: https://www.example.com/support/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers: []
paths: {}
